//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type User struct {
	ID               int64 `sql:"primary_key"`
	TokenNumber      int16
	UseTrial         bool
	InviteCode       uuid.UUID
	CreatedAt        time.Time
	IsPayedTale      bool
	FirstName        *string
	LastName         *string
	TelegramUsername *string
}
